export const ApiPayload = (user:userInfo) => {
  return {
    userId: "10aec560-b9d7-44ad-9d9b-4e44c433fe75",
    user: {
      id: null,
      Id: "00000000-0000-0000-0000-000000000000",
      FullAccess: false,
      TempId: "477f5052-028d-2af8-3562-598dd230103d",
      userRoles: [],
      userLocations: [],
      userReportRole: [],
      ServiceProviderType: 1,
      TerritoryId: null,
      OrganizationId: "00000000-0000-0000-0000-000000000000",
      BusinessUnitId: "00000000-0000-0000-0000-000000000000",
      ParentSystemUserId: null,
      FirstName: null,
      Salutation: null,
      MiddleName: null,
      LastName: null,
      PersonalEMailAddress: null,
      FullName: user.userFullName,
      NickName: null,
      Title: null,
      InternalEMailAddress: user.userEmail,
      JobTitle: null,
      MobileAlertEMail: null,
      PreferredEmailCode: null,
      HomePhone: null,
      MobilePhone:user.userNumber,
      PreferredPhoneCode: null,
      PreferredAddressCode: null,
      PhotoUrl: null,
      DomainName: null,
      PassportLo: null,
      CreatedOn: "1/1/0001 12:00:00 AM",
      PassportHi: null,
      DisabledReason: null,
      ModifiedOn: "1/1/0001 12:00:00 AM",
      CreatedBy: null,
      EmployeeId: null,
      ModifiedBy: null,
      IsDisabled: null,
      GovernmentId: null,
      VersionNumber: null,
      Skills: null,
      DisplayInServiceViews: null,
      CalendarId: null,
      ActiveDirectoryGuid: null,
      SetupUser: false,
      SiteId: null,
      WindowsLiveID: null,
      IncomingEmailDeliveryMethod: 0,
      OutgoingEmailDeliveryMethod: 0,
      ImportSequenceNumber: null,
      AccessMode: 0,
      InviteStatusCode: null,
      IsActiveDirectoryUser: false,
      OverriddenCreatedOn: null,
      UTCConversionTimeZoneCode: null,
      TimeZoneRuleVersionNumber: null,
      YomiFullName: null,
      YomiLastName: null,
      YomiMiddleName: null,
      YomiFirstName: null,
      CreatedOnBehalfBy: null,
      ExchangeRate: null,
      IsIntegrationUser: false,
      ModifiedOnBehalfBy: null,
      EmailRouterAccessApproval: 0,
      DefaultFiltersPopulated: false,
      CALType: 0,
      QueueId: null,
      TransactionCurrencyId: null,
      IsSyncWithDirectory: false,
      IsLicensed: false,
      dm_EmailPassword: "R3656wp",
      dm_EmailOutGoingMailServer: null,
      dm_EmailPort: null,
      dm_EmailSSL: 0,
      dm_Login: user.userLoginName,
      dm_LoginPassword: user.userPassword,
      dm_changePassword: 0,
      dm_AvailableToAllLocations: 0,
      dm_Location: user.userLocation,
      DefaultPage: null,
      dm_Inactive: null,
      DefaultDashboard: null,
      dm_Newfeature: null,
      dm_Theme: null,
      dm_R365: 0,
      dm_AllReports: 0,
      IsServiceProvider: false,
      ServiceProvider: 0,
      AllReports: false,
      availableToAllLocations: false,
      isServiceProvider: false,
    },
  };
};

export interface userInfo{
    userFullName:string;
    userLoginName:string;
    userPassword:string;
    userLocation:string;
    userNumber:string;
    userEmail:string;
}